services:
  casabella:
    image: casabella-api
    container_name: casabella-api

    build: .

    ports:
      - "5000:5000"

    volumes:
      - .:/app
      - node_modules:/app/node_modules
      - ./uploads:/app/uploads

    env_file:
      - ./config/.env

    command: npm run dev

volumes:
  node_modules: